import React,{useEffect,useMemo,useState} from 'react'; import {createRoot} from 'react-dom/client'; import './styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:4000';
type Course={id:string;name:string;code:string;color:string}; type Task={id:string;title:string;description?:string;dueAt:string;status:'TODO'|'IN_PROGRESS'|'DONE';priority:number;course?:Course}; type User={id:string;name:string;email:string;role:'STUDENT'|'ADMIN'};
async function api(path:string,opts:RequestInit={}){const token=localStorage.getItem('token');const res=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});if(!res.ok)throw new Error((await res.json()).message||'Request failed');return res.status===204?null:res.json()}
function App(){const [user,setUser]=useState<User|null>(()=>JSON.parse(localStorage.getItem('user')||'null')); const [authMode,setAuthMode]=useState<'login'|'register'>('login'); const [tasks,setTasks]=useState<Task[]>([]); const [courses,setCourses]=useState<Course[]>([]); const [showForm,setShowForm]=useState(false); const [error,setError]=useState('');
 const load=async()=>{try{const [t,c]=await Promise.all([api('/api/tasks'),api('/api/courses')]);setTasks(t);setCourses(c)}catch(e:any){setError(e.message)}}; useEffect(()=>{if(user)load()},[user]);
 const stats=useMemo(()=>({open:tasks.filter(t=>t.status!=='DONE').length,urgent:tasks.filter(t=>t.status!=='DONE'&&(new Date(t.dueAt).getTime()-Date.now())<48*3600000).length,done:tasks.filter(t=>t.status==='DONE').length}),[tasks]);
 if(!user)return <Auth mode={authMode} setMode={setAuthMode} onLogin={(u,t)=>{localStorage.setItem('token',t);localStorage.setItem('user',JSON.stringify(u));setUser(u)}}/>;
 const logout=()=>{localStorage.clear();setUser(null)};
 const addTask=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/tasks',{method:'POST',body:JSON.stringify({title:f.get('title'),dueAt:new Date(String(f.get('dueAt'))).toISOString(),priority:Number(f.get('priority')),courseId:f.get('courseId')||undefined})});e.currentTarget.reset();setShowForm(false);load()}catch(e:any){setError(e.message)}};
 const cycle=async(t:Task)=>{const next=t.status==='TODO'?'IN_PROGRESS':t.status==='IN_PROGRESS'?'DONE':'TODO';await api('/api/tasks/'+t.id,{method:'PATCH',body:JSON.stringify({status:next})});load()};
 return <div className="app"><header><div className="brand">Campus<span>Flow</span></div><div className="user">{user.name}<button onClick={logout}>Log out</button></div></header><main><section className="hero"><div><p className="eyebrow">YOUR ACADEMIC COMMAND CENTER</p><h1>Know what matters <em>next.</em></h1><p className="sub">One calm view of every deadline, course and priority.</p></div><button className="primary" onClick={()=>setShowForm(true)}>+ Add task</button></section>{error&&<div className="error">{error}</div>}<section className="stats"><Stat n={stats.open} label="Open tasks"/><Stat n={stats.urgent} label="Due in 48h"/><Stat n={stats.done} label="Completed"/></section><section className="content"><div className="panel"><div className="panelHead"><h2>Upcoming</h2><span>{tasks.length} total</span></div>{tasks.length===0?<div className="empty">No tasks yet. Add your first deadline.</div>:tasks.map(t=><article className={`task ${t.status==='DONE'?'done':''}`} key={t.id}><button className="check" onClick={()=>cycle(t)}>{t.status==='DONE'?'✓':''}</button><div className="taskMain"><strong>{t.title}</strong><div><span className="course">{t.course?.code||'General'}</span><span className="due">{new Date(t.dueAt).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</span></div></div><span className={`priority p${t.priority}`}>{t.priority===1?'High':t.priority===2?'Medium':'Low'}</span></article>)}</div><aside className="panel courses"><div className="panelHead"><h2>Courses</h2><span>{courses.length}</span></div>{courses.map(c=><div className="courseRow" key={c.id}><div className="dot"/><div><strong>{c.code}</strong><small>{c.name}</small></div></div>)}{courses.length===0&&<div className="empty">Create courses from the API or seed.</div>}</aside></section></main>{showForm&&<div className="modal"><form onSubmit={addTask}><div className="modalHead"><h2>New task</h2><button type="button" onClick={()=>setShowForm(false)}>×</button></div><label>Task title<input name="title" required placeholder="e.g. Marketing case study"/></label><label>Due date & time<input name="dueAt" type="datetime-local" required/></label><label>Priority<select name="priority" defaultValue="2"><option value="1">High</option><option value="2">Medium</option><option value="3">Low</option></select></label><label>Course<select name="courseId"><option value="">General</option>{courses.map(c=><option value={c.id} key={c.id}>{c.code} — {c.name}</option>)}</select></label><button className="primary">Create task</button></form></div>}</div>}
function Stat({n,label}:{n:number;label:string}){return <div className="stat"><b>{n}</b><span>{label}</span></div>}
function Auth({mode,setMode,onLogin}:{mode:'login'|'register';setMode:(m:'login'|'register')=>void;onLogin:(u:User,t:string)=>void}){const [err,setErr]=useState('');const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await api('/api/auth/'+mode,{method:'POST',body:JSON.stringify(mode==='register'?{name:f.get('name'),email:f.get('email'),password:f.get('password')}:{email:f.get('email'),password:f.get('password')})});onLogin(r.user,r.token)}catch(e:any){setErr(e.message)}};return <div className="auth"><div className="authCard"><div className="brand">Campus<span>Flow</span></div><p className="eyebrow">ACADEMIC PLANNER</p><h1>{mode==='login'?'Welcome back':'Build your study system'}</h1><p className="sub">{mode==='login'?'Pick up where you left off.':'Turn deadlines into a plan you can actually follow.'}</p><form onSubmit={submit}>{mode==='register'&&<label>Name<input name="name" required/></label>}<label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength={8} required/></label>{err&&<div className="error">{err}</div>}<button className="primary">{mode==='login'?'Sign in':'Create account'}</button></form><button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?"New here? Create an account":"Already have an account? Sign in"}</button></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
