import { Router } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { prisma } from '../index.js';
const router = Router();
const credentials = z.object({ name: z.string().min(2).max(60), email: z.string().email(), password: z.string().min(8).max(100) });
router.post('/register', async (req,res,next)=>{ try { const data=credentials.parse(req.body); const exists=await prisma.user.findUnique({where:{email:data.email.toLowerCase()}}); if(exists)return res.status(409).json({message:'Email already registered'}); const password=await bcrypt.hash(data.password,12); const user=await prisma.user.create({data:{name:data.name,email:data.email.toLowerCase(),password}}); const token=jwt.sign({id:user.id,role:user.role},process.env.JWT_SECRET!,{expiresIn:'7d'}); res.status(201).json({token,user:{id:user.id,name:user.name,email:user.email,role:user.role}}); } catch(e){next(e)} });
router.post('/login', async (req,res,next)=>{ try { const email=z.string().email().parse(req.body.email).toLowerCase(); const password=z.string().min(1).parse(req.body.password); const user=await prisma.user.findUnique({where:{email}}); if(!user || !(await bcrypt.compare(password,user.password))) return res.status(401).json({message:'Invalid email or password'}); const token=jwt.sign({id:user.id,role:user.role},process.env.JWT_SECRET!,{expiresIn:'7d'}); res.json({token,user:{id:user.id,name:user.name,email:user.email,role:user.role}}); } catch(e){next(e)} });
export default router;
