import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../index.js';
import { requireAuth, AuthRequest } from '../middleware/auth.js';
const c=await prisma.course.findFirst({where:{id:String(req.params.id),ownerId:req.user!.id}});
router.use(requireAuth);
router.get('/',async(req:AuthRequest,res,next)=>{try{res.json(await prisma.course.findMany({where:{ownerId:req.user!.id},include:{_count:{select:{tasks:true}}},orderBy:{createdAt:'asc'}}))}catch(e){next(e)}});
router.post('/',async(req:AuthRequest,res,next)=>{try{res.status(201).json(await prisma.course.create({data:{...body.parse(req.body),ownerId:req.user!.id}}))}catch(e){next(e)}});
router.delete('/:id',async(req:AuthRequest,res,next)=>{try{const c=await prisma.course.findFirst({where:{id:req.params.id,ownerId:req.user!.id}});if(!c)return res.status(404).json({message:'Course not found'});await prisma.course.delete({where:{id:c.id}});res.status(204).end()}catch(e){next(e)}});
export default router;
