import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../index.js';
import { requireAuth, requireRole, AuthRequest } from '../middleware/auth.js';
const router=Router(); router.use(requireAuth);
const taskBody=z.object({title:z.string().min(2).max(120),description:z.string().max(500).optional(),dueAt:z.string().datetime(),priority:z.number().int().min(1).max(3).default(2),courseId:z.string().optional()});
router.get('/',async(req:AuthRequest,res,next)=>{try{const tasks=await prisma.task.findMany({where:{ownerId:req.user!.id},include:{course:true},orderBy:{dueAt:'asc'}});res.json(tasks)}catch(e){next(e)}});
router.post('/',async(req:AuthRequest,res,next)=>{try{const data=taskBody.parse(req.body);if(data.courseId){const c=await prisma.course.findFirst({where:{id:data.courseId,ownerId:req.user!.id}});if(!c)return res.status(400).json({message:'Invalid course'})}res.status(201).json(await prisma.task.create({data:{...data,dueAt:new Date(data.dueAt),ownerId:req.user!.id}}))}catch(e){next(e)}});
router.patch('/:id',async(req:AuthRequest,res,next)=>{try{const task=await prisma.task.findFirst({where:{id:String(req.params.id),ownerId:req.user!.id}});if(!task)return res.status(404).json({message:'Task not found'});const status=z.enum(['TODO','IN_PROGRESS','DONE']).optional().parse(req.body.status);res.json(await prisma.task.update({where:{id:task.id},data:{status}}))}catch(e){next(e)}});
router.delete('/:id',async(req:AuthRequest,res,next)=>{try{const task=await prisma.task.findFirst({where:{id:String(req.params.id),ownerId:req.user!.id}});if(!task)return res.status(404).json({message:'Task not found'});await prisma.task.delete({where:{id:task.id}});res.status(204).end()}catch(e){next(e)}});
router.get('/admin/all',requireRole('ADMIN'),async(_req,res,next)=>{try{res.json(await prisma.task.findMany({include:{owner:{select:{name:true,email:true}},course:true},orderBy:{dueAt:'asc'},take:100}))}catch(e){next(e)}});
export default router;
