import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { PrismaClient } from '@prisma/client';
import authRoutes from './routes/auth.js';
import courseRoutes from './routes/courses.js';
import taskRoutes from './routes/tasks.js';
import { errorHandler } from './middleware/error.js';
export const prisma = new PrismaClient();
const app = express();
app.use(cors({ origin: process.env.CLIENT_URL?.split(',') ?? true }));
app.use(express.json());
app.get('/health', (_req, res) => res.json({ ok: true, service: 'campusflow-api' }));
app.use('/api/auth', authRoutes);
app.use('/api/courses', courseRoutes);
app.use('/api/tasks', taskRoutes);
app.use(errorHandler);
const port = Number(process.env.PORT ?? 4000);
if (process.env.NODE_ENV !== 'test') app.listen(port, () => console.log(`API listening on ${port}`));
export default app;
