CREATE TYPE "Role" AS ENUM ('STUDENT','ADMIN');
CREATE TYPE "TaskStatus" AS ENUM ('TODO','IN_PROGRESS','DONE');
CREATE TABLE "User" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT NOT NULL,"password" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'STUDENT',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Course" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"color" TEXT NOT NULL DEFAULT 'indigo',"ownerId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Course_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Task" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"dueAt" TIMESTAMP(3) NOT NULL,"status" "TaskStatus" NOT NULL DEFAULT 'TODO',"priority" INTEGER NOT NULL DEFAULT 2,"ownerId" TEXT NOT NULL,"courseId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Task_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
ALTER TABLE "Course" ADD CONSTRAINT "Course_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE SET NULL ON UPDATE CASCADE;
